// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

import { KiwiManifest } from "@kiwi-app/nextjs";

import * as $0 from "@/sections/footer";
import * as $1 from "@/sections/navbar";
import * as $2 from "@/sections/redux-usage";
import * as $3 from "@/sections/with-loader";

const manifest: KiwiManifest = {
  sections: {
    "@/sections/footer": {
      module: $0,
      schema: {
        component: {
          type: "object",
          required: ["menus"],
          properties: [
            {
              name: "menus",
              type: "array",
              items: {
                type: "object",
                required: ["title", "items"],
                properties: [
                  { name: "title", type: "string" },
                  {
                    name: "items",
                    type: "array",
                    items: {
                      type: "object",
                      required: ["name", "href"],
                      properties: [
                        { name: "name", type: "string" },
                        { name: "href", type: "string" },
                      ],
                    },
                  },
                ],
              },
            },
          ],
        },
      },
    },
    "@/sections/navbar": {
      module: $1,
      schema: {
        component: {
          type: "object",
          required: ["items"],
          properties: [
            {
              name: "items",
              type: "array",
              items: {
                type: "object",
                required: ["name", "href"],
                properties: [
                  { name: "name", type: "string" },
                  { name: "href", type: "string" },
                  {
                    name: "subItems",
                    type: "array",
                    items: {
                      type: "object",
                      required: ["name", "href"],
                      properties: [
                        { name: "name", type: "string" },
                        { name: "href", type: "string" },
                      ],
                    },
                  },
                ],
              },
            },
          ],
        },
      },
    },
    "@/sections/redux-usage": {
      module: $2,
      schema: {
        component: {
          type: "object",
          required: ["title", "initialValue"],
          properties: [
            { name: "title", type: "string" },
            { name: "initialValue", type: "number" },
          ],
        },
      },
    },
    "@/sections/with-loader": {
      module: $3,
      schema: {
        component: {
          type: "object",
          required: ["title", "loader"],
          properties: [{ name: "title", type: "RichText" }],
        },
        loader: {
          type: "object",
          required: ["items"],
          properties: [
            {
              name: "items",
              type: "number",
              description: "amount of products loaded. default: 5",
            },
          ],
        },
      },
    },
  },
  site: "kiwi-template",
};

export default manifest;
