// DO NOT REMOVE. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

import manifest from "@manifest";
import { KiwiOptions } from "@kiwi-app/nextjs";

const options: KiwiOptions = {
  manifest,
};

export default options;
