// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

import options from "@kiwi-options";
import { LiveRoute } from "@kiwi-app/nextjs";

export const { GET, POST, OPTIONS, PATCH } = LiveRoute(options);
