"use client";

// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

import options from "@kiwi-options";
import { CatchAllClient } from "@kiwi-app/nextjs";

const Page = CatchAllClient(options);

export default Page;
