// DO NOT EDIT. This file is generated by Kiwi.
// This file SHOULD be checked into source version control.

import options from "@kiwi-options";
import { CatchAll } from "@kiwi-app/nextjs";
import ClientComponent from "./client";
import ServerComponent from "./server";

const Page = CatchAll(options, ClientComponent, ServerComponent);

export default Page;
